#!/usr/bin/env python3
"""Embed a text file into a C++ raw string literal."""
import sys


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: embed.py <input> <output>", file=sys.stderr)
        return 2
    src, dst = sys.argv[1], sys.argv[2]
    with open(src, "rb") as fh:
        data = fh.read().decode("utf-8")

    delim = "POLYEMBED"
    while (")" + delim + '"') in data:
        delim += "X"

    with open(dst, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("// Generated by tools/embed.py - do not edit.\n")
        fh.write("namespace poly {\n")
        fh.write("const char* embedded_testlib_source() {\n")
        fh.write("    return R\"" + delim + "(" + data + ")" + delim + "\";\n")
        fh.write("}\n")
        fh.write("}  // namespace poly\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
